protected/backend/controllers/SiteController.php
<?php
class SiteController extends Controller
{ 
	public $layout='main';

	/**
	 * Declares class-based actions.
	 */
	public function beforeAction($action)
	{
	
	  //Yii::app()->user->logout(); 
		if(!isset(Yii::app()->user->roleid) and Yii::app()->request->getPathInfo()!='admin')
		{
			 
			//Yii::app()->user->setState("urls",Yii::app()->request->url);
			$this->redirect(Yii::app()->user->loginUrl);
		}
		else
		{
			 
			return true;
		}
    
     
	}
	public function actions()
	{  
		return array(
			// captcha action renders the CAPTCHA image displayed on the contact page
			'captcha'=>array(
				'class'=>'CCaptchaAction',
				'backColor'=>0xFFFFFF,
			),
			// page action renders "static" pages stored under 'protected/views/site/pages'
			// They can be accessed via: index.php?r=site/page&view=FileName
			'page'=>array(
				'class'=>'CViewAction',
			),
		);
	}

	/**
	 * This is the action to handle external exceptions.
	 */
	/* 
	public function actionError()
	{
	    if($error=Yii::app()->errorHandler->error)
	    {
	    	if(Yii::app()->request->isAjaxRequest)
	    		echo $error['message'];
	    	else
	        	$this->render('error', $error);
	    }
	}
    */

	/**
	 * Displays the contact page
	 */
 
	public function actionContact()
	{
		 $this->layout="column2";
		 $model=new ContactForm;
		if(isset($_POST['ContactForm']))
		{
			$model->attributes=$_POST['ContactForm'];
			if($model->validate())
			{
				$headers="From: {$model->email}\r\nReply-To: {$model->email}";
				mail(Yii::app()->params['adminEmail'],$model->subject,$model->body,$headers);
				Yii::app()->user->setFlash('contact','Thank you for contacting us. We will respond to you as soon as possible.');
				$this->refresh();
			}
		}
		$this->render('contact',array('model'=>$model));
	}
	public function actionAdduser($id=null)
	{
		 
		$this->layout="column2";
		$model=new User;
		if($id)
		{
			$model=$model->findByPk($id);
			
			$model->setScenario("update");
			$msg="Edited";
			
		}
		else
		{
			$model=new User;
			$model->setScenario("insert");
			$msg="Added";
	    }
		
		
		if(Yii::app()->request->isPostRequest)
		{
			$model->attributes=$_POST['User'];
			
			$rnd = rand(0,9999);
			$uploadedFile=CUploadedFile::getInstance($model,'image');
			
			if($model->validate())
			{
			 if($model->id)
			 {
				 unset($model->password);
		    
		     }
		     else
		     {
			 $pass=$model->password;
			 $model->password= md5($pass);
			 $model->conpassword= md5($pass);
			 }
			 
			 if(!empty($uploadedFile))
			 {
			 $fileName = "{$rnd}-{$uploadedFile}";   
             $model->image = $fileName;
		     }
		
			 if($model->save())	
			 { 
				if(!empty($uploadedFile))
				{
			    $uploadedFile->saveAs(Yii::app()->basePath.'/../uploads/admin_image/'.$fileName); 
		     	}
				Yii::app()->user->setFlash('success',"Suuccessfully {$msg}");
				$this->redirect('listuser');
			 }
			 else
			 {
				 
				print_r($model->getErrors());exit;
			 }
			}
			 
		}
		
		$this->render("adduser",array("model"=>$model));
	}
	public function actionListuser()
	{
		 
		$this->layout="column2";
		$model=new User;
		$model=$model->findAll();
		$this->render("listuser",array("model"=>$model));
	}
	public function actionDeleteuser($id=null)
	{
		 
		$this->layout="column2";
		$model=new User;
		 
		if($model->deleteByPk($id))
		{
			Yii::app()->user->setFlash('success',"successfully Deleted");
		}
		else
		{
			Yii::app()->user->setFlash('success',"Failed to Deleted");
		}
		$this->redirect(Yii::app()->request->urlReferrer);
	}

    public function actionListuserstatus($id=null,$status=null)
	{
		
		$model=new User;
		if($status=='1')
		{
			$status='0';
		}
		else
		{
			$status='1';
		}
		 
		$model=$model->findByPk($id);
		$model->status=$status;
        $model->update();
		 
		$this->redirect(Yii::app()->request->urlReferrer);
		
	}


	/**
	 * Displays the login page
	 */
	public function actionLogin()
	{
	 
		//if (!defined('CRYPT_BLOWFISH')||!CRYPT_BLOWFISH)
		//throw new CHttpException(500,"This application requires that PHP was compiled with Blowfish support for crypt().");
        $this->layout="login";
		$model=new User;

		// if it is ajax validation request
		 

		// collect user input data
		
		if(isset($_POST['User']))
		{
			if(isset($_POST['yt1']))
			{
				$email = $_POST['User']['email'];
				$pwd = $model->find();
				//print_r($pwd);
				//print_r($pwd['password']);
				//echo 'dsfsd';exit;
			}
			else
			{	
			$model->setScenario("login") ;
			$model->attributes=$_POST['User'];
			 
			 // validate user input and redirect to the previous page if valid
		    	if($model->validate())
				 {
					 if($model->checklogin($model->username,$model->password))
					 {
						 
						  $this->redirect(Yii::app()->request->baseUrl.'/'.Yii::app()->params['adminUrl']."site/adminhome");
					   
					 }
				 }
			  }	 
		  }
		// display the login form
		$this->render('login',array('model'=>$model));
	}
	//===================change password===============================
	
	
	public function actionChangepassword()
	{
	    $this->layout="column2";
		$model=new User;
          $id=Yii::app()->user->roleid;
         

		// if it is ajax validation request
		 

		// collect user input data
		if(isset($_POST['User']))
		{
			$model->setScenario("changepassword") ;
			$model->attributes=$_POST['User'];
			 
			 // validate user input and redirect to the previous page if valid
		    	if($model->validate())
				 {
					 
					 $pass=$model->password;
					 $model=$model->findByPk($id);
			         $model->password= md5($pass);
			         $model->conpassword= md5($pass);
			        if($model->update())
			        {
			         Yii::app()->user->setFlash('success',"Password successfully Changed");
			         $this->redirect(Yii::app()->request->baseUrl.'/'.Yii::app()->params['adminUrl']."site/adminhome");
				     }					
				 }
				 
		  }
		
		$this->render('changepass',array('model'=>$model));
	}
	
	public function actionAdminlinksadd($id=null)
	{
		$this->layout="column2";
		
		if($id)
		{
			$model=new AdminLinks;
			$model=$model->findByPk($id);
			$msg="Edited";
		}
		else
		{
			$model=new AdminLinks;
			$msg="Added";
		}
		if(Yii::app()->request->isPostRequest)
		{
			// print_r($_POST);exit;
			$model->attributes=$_POST['AdminLinks'];
			if($model->parent_id==null) $model->parent_id=0;
			if($model->save())
			{
				Yii::app()->user->setFlash('success',"Suuccessfully {$msg}");
				$this->redirect('adminlinks');
			}
			 
		}
		$this->render('adminlinks',array('model'=>$model));
	}
	public function actionAdminlinksdelete($id=null)
	{
		 
		$this->layout="column2";
		$model=new AdminLinks;
		 
		if($model->deleteByPk($id))
		{
			Yii::app()->user->setFlash('success',"successfully Deleted");
		}
		else
		{
			Yii::app()->user->setFlash('success',"Failed to Deleted");
		}
		$this->redirect(Yii::app()->request->urlReferrer);
	}
	public function actionAdminlinks($id=null)
	{
		  $this->layout="column2";
		  $model=new AdminLinks;
		   if(Yii::app()->request->isPostRequest)
		   {
			   if(isset($_POST['priority']))
			   {
				  foreach($_POST['priority'] as $k=>$v) 
				  {
					$model=new AdminLinks;
					$model=$model->findByPk($k) ;
					$model->priority=$v;
					$model->update(); 
				  }
				  Yii::app()->user->setFlash('success',"Priority Successfully Updated");
				  $this->refresh();
			   }
		   }
		    
			$main=$model->findAll(array('condition'=>'parent_id=0','order'=>'priority asc'));
            $sub=$model->findAll(array('condition'=>'parent_id!=0','order'=>'priority asc'));
		    $this->render('adminlinkslist',array('main'=>$main,'sub'=>$sub));
	}
	public function actionAdminlinksstatus($id=null,$status=null)
	{
		
		$model=new AdminLinks;
		if($status=='1')
		{
			$status='0';
		}
		else
		{
			$status='1';
		}
		 
		$model=$model->findByPk($id);
		$model->status=$status;
        $model->update();
		 
		$this->redirect(Yii::app()->request->urlReferrer);
		
	}
	public function actionAdminhome()
	{
	    $this->layout="column2";
		$this->render('adminhome');
	}

	/**
	 * Logs out the current user and redirect to homepage.
	 */
	public function actionLogout()
	{
		 
		Yii::app()->user->logout();
		$this->redirect(Yii::app()->user->loginUrl);
	}
}

protected/backend/views/site/adduser.php
 <style>
 .form-control{ max-width:300px;}
 </style>
              <div class="col-lg-6" style="width:100%">
                <div class="box dark">
                  <header>
                    <div class="icons">
                      <i class="fa fa-edit"></i>
                    </div>
                    <h5><?php if($model->id==null){ ?>Add<? }else {?>Edit<?}?>  User</h5>
                   <div style="float:right;padding: 10px 15px;"> <a href="listuser" class='btn btn-metis-3 btn-sm btn-flat'>All Users
                  </a>
                  </div>
                    <!-- .toolbar 
                    <div class="toolbar">
                      <nav style="padding: 8px;">
                        <a href="javascript:;" class="btn btn-default btn-xs collapse-box">
                          <i class="fa fa-minus"></i>
                        </a> 
                        <a href="javascript:;" class="btn btn-default btn-xs full-box">
                          <i class="fa fa-expand"></i>
                        </a> 
                        <a href="javascript:;" class="btn btn-danger btn-xs close-box">
                          <i class="fa fa-times"></i>
                        </a> 
                      </nav>
                    </div><!-- /.toolbar -->
                  </header>
                  <div id="div-1" class="body">
              
					<?php
					$form=$this->beginWidget('CActiveForm', array(
					'htmlOptions'=>array('class'=>'form-horizontal','enctype' => 'multipart/form-data'),
					'enableClientValidation'=>true,
					//   'enableAjaxValidation'=>true,
					'clientOptions'=>array(
					'validateOnSubmit'=>true,
					),
					)); 

					?>
						<div class="form-group">
						<?php echo $form->labelEx($model,'first_name',array('class'=>'control-label col-lg-4')); ?>               
						<div class="col-lg-8">
						<?php echo $form->textField($model,'first_name',array('class'=>'form-control','placeholder'=>"First Name")); ?>
						 <?php echo $form->error($model,'first_name',array('class'=>'text-danger')); ?>
						</div>
						</div>
						
						<div class="form-group">
						<?php echo $form->labelEx($model,'last_name',array('class'=>'control-label col-lg-4')); ?>               
						<div class="col-lg-8">
						<?php echo $form->textField($model,'last_name',array('class'=>'form-control','placeholder'=>"Last Name")); ?>
						 <?php echo $form->error($model,'last_name',array('class'=>'text-danger')); ?>
						</div> 
						</div>
						
						<div class="form-group">
						<?php echo $form->labelEx($model,'email',array('class'=>'control-label col-lg-4')); ?>               
						<div class="col-lg-8">
						<?php echo $form->textField($model,'email',array('class'=>'form-control','placeholder'=>"Email")); ?>
						<?php echo $form->error($model,'email',array('class'=>'text-danger')); ?>
						</div> 
						</div>
						
                        <div class="form-group">
						<?php echo $form->labelEx($model,'username',array('class'=>'control-label col-lg-4')); ?>               
                        <div class="col-lg-8">
						<?php echo $form->textField($model,'username',array('class'=>'form-control','placeholder'=>"User Name")); ?>
                        <?php echo $form->error($model,'username',array('class'=>'text-danger')); ?>
                        </div>
                         </div>
                         <?php if($model->id==null)
                         {
							 ?>
                         <div class="form-group">
						<?php echo $form->labelEx($model,'password',array('class'=>'control-label col-lg-4')); ?>               
                        <div class="col-lg-8">
						<?php echo $form->passwordField($model,'password',array('class'=>'form-control','placeholder'=>"Password")); ?>
                        <?php echo $form->error($model,'password',array('class'=>'text-danger')); ?>
                        </div>
                         </div>
                         <div class="form-group">
						<?php echo $form->labelEx($model,'conpassword',array('class'=>'control-label col-lg-4')); ?>               
                        <div class="col-lg-8">
						<?php echo $form->passwordField($model,'conpassword',array('class'=>'form-control','placeholder'=>"Confirm Password")); ?>
                        <?php echo $form->error($model,'conpassword',array('class'=>'text-danger')); ?>
                        </div>
                         </div>
                        <?php 
					    
					    }
					    ?>
                        <div class="form-group">
						<?php echo $form->labelEx($model,'role',array('class'=>'control-label col-lg-4')); ?>               
                        <div class="col-lg-8">
						 
						 <?php echo $form->dropDownList($model,'role',array("A"=>"Admin","U"=>"User"),array("empty"=>"Select Role",'class'=>'form-control')); ?>
						 <?php echo $form->error($model,'role',array('class'=>'text-danger')); ?>
                        </div>
                         </div>
                           <div class="form-group">
						<?php echo $form->labelEx($model,'image',array('class'=>'control-label col-lg-4')); ?>               
                        <div class="col-lg-8">
						 <?php echo $form->fileField($model,'image'); ?>
						 <?php echo $form->error($model,'image',array('class'=>'text-danger')); ?>
						 <?php echo CHtml::image(Yii::app()->request->baseUrl.'/uploads/admin_image/'.$model->image, '',array("style"=>"width:100px;margin:10px 0px;")); ?>
                        </div>
                         </div>
                          
                         
                         
                        <div class="form-group">
						       <label  class = 'control-label col-lg-4'>&nbsp;</label>   
                        <div class="col-lg-8">
						 <?php echo CHtml::submitButton('Save',array('class'=>'btn btn-metis-5 btn-sm btn-flat')); ?>
                        </div>
                         </div>
       
                     <?php $this->endWidget(); ?>
                  </div>
                </div>
              </div>

protected/backend/views/site/adminhome.php
 <style>
 .form-control{ max-width:300px;}
 </style>
              <div class="col-lg-6" style="width:100%">
                <div class="box dark">
                  <header>
                    <div class="icons">
                      <i class="glyphicon glyphicon-home"></i>
                    </div>
                    <h5>Home</h5>
                    <div style="text-align:center;margin-top:3px;" >	<span class="label label-success" style="text-align:center"><?php echo Yii::app()->user->getFlash('success');?></span></div>
                
                    <!-- .toolbar 
                    <div class="toolbar">
                      <nav style="padding: 8px;">
                        <a href="javascript:;" class="btn btn-default btn-xs collapse-box">
                          <i class="fa fa-minus"></i>
                        </a> 
                        <a href="javascript:;" class="btn btn-default btn-xs full-box">
                          <i class="fa fa-expand"></i>
                        </a> 
                        <a href="javascript:;" class="btn btn-danger btn-xs close-box">
                          <i class="fa fa-times"></i>
                        </a> 
                      </nav>
                    </div><!-- /.toolbar -->
                  </header>
                  <div id="div-1" class="body">
                              <pre>
								  <h2 class="text-primary" style="text-align:center;color:black"> Welcome To The Administrative Console of</h2>
								  <br />
                                  <div   style="text-align:center;"><img src="<?php echo Yii::app()->request->baseUrl;?>/images/logo.jpg" alt=""></div>
                              </pre>
                </div>
              </div>

protected/backend/views/site/adminlinkslist.php
 <?php

   function addtoglobal($id,$name)
						   {
							   
							   global $ar;
							   global $level;
							   $space=array("1"=>"<i class='glyphicon glyphicon-home' style='margin:0px 5px'></i>","2"=>"<i class='glyphicon glyphicon-plus' style='margin:0px 5px 0px 22px'></i>","3"=>"<i class='glyphicon glyphicon-minus' style='margin:0px 5px 0px 41px'></i>","4"=>"----","5"=>"-----","6"=>"------");
							    
							   $ar[$id]=$space[$level].$name;
						   }
						   function checksub($id,$parent,$name)
						   {
							   
							    global $ar;
							    global $level;
							    //global $space;
							    $space=array("1"=>"<i class='glyphicon glyphicon-home' style='margin:0px 5px'></i>","2"=>"<i class='glyphicon glyphicon-plus' style='margin:0px 5px 0px 22px'></i>","3"=>"<i class='glyphicon glyphicon-minus' style='margin:0px 5px 0px 41px'></i>","4"=>"----","5"=>"-----","6"=>"------");
							    
 
								$ar[$id]= $space[$level].$name;$level++;
							   // echo  $name;echo "<br />";
							   
							    foreach($parent[$id] as $k=>$v)
							    {
									 
									if(array_key_exists($k,$parent))
									{
									
									checksub($k,$parent,$v);
									
									}
									else
									{
									//$level++;
									//echo  '&nbsp;&nbsp;&nbsp;'.$v;echo "<br />";
									$ar[$k]=  $space[$level].$v;
								    }
								}
							   
							    $level--;
						   }
?>
                     <?php
                         
                        
                          
						   if($main)
						   {
							   
						   foreach($main as $k=>$v)
						   {
							   $GLOBALS['linkpriority'][$v->id]=$v->priority;
							   $GLOBALS['linkstatus'][$v->id]=$v->status;
							   $GLOBALS['linkurl'][$v->id]=$v->link_url;
							   //$GLOBALS['linkimage'][$v->id]=$v->link_image;
							   $mains[$v->id]=$v->link_name;
						   }
						   
						   foreach($sub as $k=>$v)
						   {
							   $GLOBALS['linkpriority'][$v->id]=$v->priority;
							   $GLOBALS['linkstatus'][$v->id]=$v->status;
							   $GLOBALS['linkurl'][$v->id]=$v->link_url;
							   $parent[$v->parent_id][$v->id]= $v->link_name; ;
						   }
						   if(!isset($parent))
						   {
							  $parent=array();
						   }
						   
						  
						   foreach($main as $k=>$v)
						   {
							   $GLOBALS['level']=1;
							   
							   if(array_key_exists($v->id,$parent))
							   {
								   
								   checksub($v->id,$parent,$v->link_name);
							   }
							   else
							   {
								 //  $ar[$v->id]=$v->link_name;
								   addtoglobal($v->id,$v->link_name);
								  // echo $level.$v->link_name.'___id:'.$v->id;echo "<br />";
							   }
						   }
						
						  }
						    if(!isset($GLOBALS['ar']))
						    {
							 
								$GLOBALS['ar']=array();
							}
						    
                        ?>
<div class="row">
<div style="text-align:center;margin-top:3px;" >	<span class="label label-success" style="text-align:center"><?php echo Yii::app()->user->getFlash('success');?></span></div>
              <div class="col-lg-12">
                <div class="box">
                  <header>
                    <div class="icons">
                      <i class="fa fa-table"></i>
                    </div>
                    <h5>List Links</h5>
                    <div style="float:right;padding: 10px 15px;"> <a href="adminlinksadd" <?php echo CHtml::submitButton('',array('class'=>'btn btn-metis-3 btn-sm btn-flat')); ?>Add New Links
                  </a>
                  </div>
                  </header>
                  <div id="collapse4" class="body">
				  <form method="post">
                    <table id="dataTable" class="table table-bordered table-condensed table-hover table-striped">
                      <thead>
                        <tr>
                          <th style="text-align:center">Sl.</th>
                          <th>Priority</th>
                          <th>Link Name</th>
                          <th>Link Url</th>
                          <th colspan="3" style="text-align:center">Action</th>
                          
                        </tr>
                      </thead>
                      <tbody>
                        <?php
					  if(!empty($GLOBALS['ar']))
					  {  
						  
						  $i=1;
						  foreach($GLOBALS['ar'] as $k=>$v)
						  {
							 
							 // print_r($GLOBALS['linkpriority'][$k]);exit;
							  ?>
							  <tr>
							  <td style="text-align:center"><?php echo  $i; ?></td>
							  <td style="text-align:center !important;">
								 
									<input type="text" class="form-control" name="priority[<?php echo $k; ?>]" style="height:30px;text-align:center;width:70px;margin:auto;" value="<?php echo $GLOBALS['linkpriority'][$k] ; ?>"  />
 
                                
							  </td>
							  <td><?php echo $v ?></td>
							  <td><?php echo  $GLOBALS['linkurl'][$k] ?></td>
							  
								  <?php
								  if($GLOBALS['linkstatus'][$k]=='0')
								  {
									   $image = CHtml::image(Yii::app()->request->baseUrl.'/images/admin/active.gif', 'Status', array('title'=>'Active'));
									   $tit="Active";
								  }
								  else
								  {
									  $image = CHtml::image(Yii::app()->request->baseUrl.'/images/admin/deactive.gif', 'Status', array('title'=>'Deactive'));
									  $tit="Deactive";
								  }
								  ?>
								   <td style="text-align:center">
									   <?
							          echo CHtml::link(CHtml::image( Yii::app()->request->baseUrl.'/images/admin/pencil.png', 'Edit', array('title'=>'Edit')),array('site/adminlinksadd','id'=>$k),array('title'=>'Edit'));  
                                      ?>
                                   </td>
                                   <td style="text-align:center">
									   <?
                                        echo CHtml::link(CHtml::image( Yii::app()->request->baseUrl.'/images/admin/cross.png', 'Delete', array('title'=>'Delete')),array('site/adminlinksdelete','id'=>$k),array('title'=>'Delete','confirm'=>'Are you sure'));  
							           ?>
							       </td>
							       <td style="text-align:center">
									<?
							        echo CHtml::link($image,array('site/adminlinksstatus','id'=>$k,'status'=>$GLOBALS['linkstatus'][$k]),array('title'=>$tit)); ?>
						 
							  </td>
							  </tr>
							  
							  <?
							  $i++;
						  }
						  	  echo "<tr><td colspan='100%' style='text-align:center'><input class=\"btn btn btn-metis-5 btn-sm btn-flat\" type=\"submit\" value=\"Update Priority\"></td></tr>";
					
					  }
					  else
					  {
						  echo "<tr><td colspan='4' style='text-align:center'>No Result Found..</td></tr>";
					  }
					  ?>
                      </tbody>
                    </table>
                    </form>
                  </div>
                </div>
              </div>
            </div><!-- /.row -->

   

protected/backend/views/site/changepass.php
 <style>
 .form-control{ max-width:300px;}
 </style>
              <div class="col-lg-6" style="width:100%">
                <div class="box dark">
                  <header>
                    <div class="icons">
                      <i class="fa fa-edit"></i>
                    </div>
                    <h5>Change Password</h5>
                   <div style="float:right;padding: 10px 15px;"> <a href="listuser" class='btn btn-metis-3 btn-sm btn-flat'>All Users
                  </a>
                  </div>
                    <!-- .toolbar 
                    <div class="toolbar">
                      <nav style="padding: 8px;">
                        <a href="javascript:;" class="btn btn-default btn-xs collapse-box">
                          <i class="fa fa-minus"></i>
                        </a> 
                        <a href="javascript:;" class="btn btn-default btn-xs full-box">
                          <i class="fa fa-expand"></i>
                        </a> 
                        <a href="javascript:;" class="btn btn-danger btn-xs close-box">
                          <i class="fa fa-times"></i>
                        </a> 
                      </nav>
                    </div><!-- /.toolbar -->
                  </header>
                  <div id="div-1" class="body">
              
					<?php
					$form=$this->beginWidget('CActiveForm', array(
					'htmlOptions'=>array('class'=>'form-horizontal','enctype' => 'multipart/form-data'),
					'enableClientValidation'=>true,
					//   'enableAjaxValidation'=>true,
					'clientOptions'=>array(
					'validateOnSubmit'=>true,
					),
					)); 

					?>
						<div class="form-group">
						<?php echo $form->labelEx($model,'password',array('class'=>'control-label col-lg-4')); ?>               
                        <div class="col-lg-8">
						<?php echo $form->passwordField($model,'password',array('class'=>'form-control','placeholder'=>"New Password")); ?>
                        <?php echo $form->error($model,'password',array('class'=>'text-danger')); ?>
                        </div>
                         </div>
                         <div class="form-group">
						<?php echo $form->labelEx($model,'conpassword',array('class'=>'control-label col-lg-4')); ?>               
                        <div class="col-lg-8">
						<?php echo $form->passwordField($model,'conpassword',array('class'=>'form-control','placeholder'=>"Confirm New Password")); ?>
                        <?php echo $form->error($model,'conpassword',array('class'=>'text-danger')); ?>
                        </div>
                         </div>
                        <?php 
					    
					    
					    ?>
                        <div class="form-group">
						       <label  class = 'control-label col-lg-4'>&nbsp;</label>   
                        <div class="col-lg-8">
						 <?php echo CHtml::submitButton('Save',array('class'=>'btn btn-metis-5 btn-sm btn-flat')); ?>
                        </div>
                         </div>
       
                     <?php $this->endWidget(); ?>
                  </div>
                </div>
              </div>

protected/backend/views/site/error.php
<?php
$this->pageTitle=Yii::app()->name . ' - Error';
$this->breadcrumbs=array(
	'Error',
);
?>

<h2>Error <?php echo $code; ?></h2>

<div class="error">
<?php echo CHtml::encode($message); ?>
</div>

protected/backend/views/site/listuser.php
<div class="row">
<div style="text-align:center;margin-top:3px;" >	<span class="label label-success" style="text-align:center"><?php echo Yii::app()->user->getFlash('success');?></span></div>
              <div class="col-lg-12">
                <div class="box">
                  <header>
                    <div class="icons">
                      <i class="fa fa-table"></i>
                    </div>
                    <h5>List User</h5><div style="float:right;padding: 10px 15px;"> <a href="adduser" <?php echo CHtml::submitButton('',array('class'=>'btn btn-metis-3 btn-sm btn-flat')); ?>Add New User
                  </a>
                  </div>
                  </header>
                  <div id="collapse4" class="body">
					
                    <table id="dataTable" class="table table-bordered table-condensed table-hover table-striped">
                      <thead>
                        <tr>
                          <th style="text-align:center">Sl.</th>
                          <th>Name</th>
                          <th>Emal</th>
                          <th>Role</th>
                         <th colspan="3" style="text-align:center">Action</th>
                          
                        </tr>
                      </thead>
                      <tbody>
                        <?php
					  if(!empty($model))
					  {  
						  
						  $i=1;
						  foreach($model as $k=>$v)
						  {
							  ?>
							  <tr>
							  <td style="text-align:center"><?php echo  $i; ?></td>
							  <td><?php echo $v->first_name;?>&nbsp;<?php echo $v->last_name;?> </td>
							  <td><?php echo $v->email; ?></td>
							  <?php $role=array("A"=>"Admin","U"=>"User");?>
							   <td><?php echo $role[$v->role]; ?></td>
							   
								  <?php
								  if($v->status=='0')
								  {
									   $image = CHtml::image(Yii::app()->request->baseUrl.'/images/admin/active.gif', 'Status', array('title'=>'Active'));
									   $tit="Active";
								  }
								  else
								  {
									  $image = CHtml::image(Yii::app()->request->baseUrl.'/images/admin/deactive.gif', 'Status', array('title'=>'Deactive'));
									  $tit="Deactive";
								  }
								  ?>
								   <td style="text-align:center">
									   <?
							          echo CHtml::link(CHtml::image( Yii::app()->request->baseUrl.'/images/admin/pencil.png', 'Edit', array('title'=>'Edit')),array('site/adduser','id'=>$v->id),array('title'=>'Edit'));  
                                      ?>
                                   </td>
                                   <td style="text-align:center">
									   <?
                                        echo CHtml::link(CHtml::image( Yii::app()->request->baseUrl.'/images/admin/cross.png', 'Delete', array('title'=>'Delete')),array('site/deleteuser','id'=>$v->id),array('title'=>'Delete','confirm'=>'Are you sure'));  
							           ?>
							       </td>
							       <td style="text-align:center">
									<?
							        echo CHtml::link($image,array('site/listuserstatus','id'=>$v->id,'status'=>$v->status),array('title'=>$tit)); ?>
						 
							  </td>	  
							  
							  
							  
							  
							  
							  
							  
							  
							  </tr>
							  
							  <?
							  $i++;
						  }
					  }
					  else
					  {
						  echo "<tr><td colspan='100%' style='text-align:center'>No Result Found..</td></tr>";
					  }
					  ?>
                      </tbody>
                    </table>
                  
                  </div>
                </div>
              </div>
            </div><!-- /.row -->

   